// Mocks generated by Mockito 5.1.0 from annotations
// in code_magic_test/test/data_fetching_test.dart.
// Do not manually edit this file.

import 'package:code_magic_test/logic/fetch_author_data.dart' as _i2;
import 'package:code_magic_test/models/author_model.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [FetchAuthors].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchAuthors extends _i1.Mock implements _i2.FetchAuthors {
  MockFetchAuthors() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.AuthorModel> serializeApiData(dynamic response) =>
      (super.noSuchMethod(Invocation.method(#serializeApiData, [response]),
          returnValue: <_i3.AuthorModel>[]) as List<_i3.AuthorModel>);
}
